name: gnome-ring
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A free, universal, communication platform which preserves privacy and freedoms
icon: icons/ring.png
description: |
  Ring is free software which allows its users to communicate in multiple ways.
  * A telephone: a simple tool to connect, communicate and share.
  * A teleconferencing tool: easily join calls to create conferences with multiple participants.
  * A media sharing tool: Ring supports a variety of video input options, including mutliple cameras and image and video files, and the selection of audio inputs and outputs; all this is supported by multiple high quality audio and video codecs.
  * A messenger: send text messeges during calls or out of calls (as long as your peer is connected).
  * A building block for your IoT project: re-use the universal communications technology of Ring with its portable library on your system of choice.

confinement: devmode # use 'strict' once you have the right plugs and slots

# slots:
#   dbus-dring:
#     interface: dbus
#     bus: session
#     name: cx.ring.Ring

apps:
  gnome-ring:
    command: desktop-launch snapcraft-preload $SNAP/usr/bin/gnome-ring
    plugs:
      - browser-support
      - camera
      - gsettings
      - home
      - network
      - opengl
      - pulseaudio
      - unity7
      - x11

  dring:
    command: desktop-launch $SNAP/usr/lib/ring/dring
    slots: [dbus-dring]
    plugs: [network]

parts:
  libring:
    source: https://github.com/savoirfairelinux/ring-daemon.git
    source-type: git
    source-depth: 1
    plugin: autotools
    configflags:
      - --prefix=/usr
    prepare: |
      sed -i 's/AC_DEFINE_UNQUOTED(\[HAVE_SHM\], .*/AC_DEFINE_UNQUOTED([HAVE_SHM], 0,/' configure.ac
      mkdir contrib/native
      cd contrib/native
      ../bootstrap
      make
    build-packages:
      - gettext
      - libasound2-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavformat-dev
      - libboost-dev
      - libdbus-c++-dev
      - libgnutls-dev
      - libgsm1-dev
      - libjack-dev
      - libjsoncpp-dev
      - libopus-dev
      - libpcre3-dev
      - libpulse-dev
      - libsamplerate0-dev
      - libsndfile1-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libsrtp0-dev
      - libswscale-dev
      - libudev-dev
      - libupnp-dev
      - libva-dev
      - libvdpau-dev
      - libyaml-cpp-dev
      - uuid-dev
      - yasm
    stage-packages:
      - libasound2
      - libavcodec-ffmpeg-extra56
      - libavdevice-ffmpeg56
      - libavformat-ffmpeg56
      - libdbus-c++-1-0v5
      - libgnutls30
      - libgnutlsxx28
      - libgsm1
      - libjack0
      - libjsoncpp1
      - libopus0
      - libpcre3
      - libpcrecpp0v5
      - libpulse0
      - libsamplerate0
      - libsndfile1
      - libspeex1
      - libspeexdsp1
      - libsrtp0
      - libswscale-ffmpeg3
      - libudev1
      - libupnp6
      - libuuid1
      - libva-egl1
      - libva-glx1
      - libva-wayland1
      - libva-x11-1
      - libva1
      - libvdpau1
      - libyaml-cpp0.5v5

  libringclient:
    after: [libring]
    source: https://github.com/savoirfairelinux/ring-lrc.git
    source-type: git
    source-depth: 1
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DRING_INCLUDE_DIR=$SNAPCRAFT_STAGE/usr/include/dring
      - -DENABLE_LIBWRAP=true
    install: |
      sed -i 's|/usr/|${PACKAGE_PREFIX_DIR}/|' \
        "$SNAPCRAFT_PART_INSTALL/usr/lib/cmake/LibRingClient/LibRingClientConfig.cmake"
    build-packages:
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
    stage-packages:
      - libegl1-mesa
      - libgl1-mesa-glx
      - libqt5concurrent5
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5printsupport5
      - libqt5sql5
      - libqt5test5
      - libqt5widgets5
      - libqt5xml5
      - libwayland-client0
      - sqlite3

  ring-client-gnome:
    after: [desktop-gtk3, libringclient, snapcraft-preload]
    source: https://github.com/savoirfairelinux/ring-client-gnome.git
    source-type: git
    source-depth: 1
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DLibRingClient_DIR=$SNAPCRAFT_STAGE/usr/lib
      - -DGSETTINGS_LOCALCOMPILE=OFF
    build-packages:
      - gettext
      - libappindicator3-dev
      - libclutter-gtk-1.0-dev
      - libebook1.2-dev
      - libgtk-3-dev
      - libnm-glib-dev
      - libnotify-dev
      - libqrencode-dev
      - libwebkit2gtk-4.0-dev
      - qtbase5-dev
    stage-packages:
      - gnome-icon-theme-symbolic
      - libappindicator3-1
      - libclutter-gtk-1.0-0
      - libebook-1.2-16
      - libegl1-mesa
      - libgl1-mesa-glx
      - libgtk-3-0
      - libnm-glib4
      - libnotify4
      - libqrencode3
      - libqt5concurrent5
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5printsupport5
      - libqt5sql5
      - libqt5test5
      - libqt5widgets5
      - libqt5xml5
      - libwayland-client0
      - libwebkit2gtk-4.0-37
      - sqlite3
